# Generated by Django 5.2 on 2025-04-07 08:41

import QrAttendanceApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrAttendanceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=QrAttendanceApp.models.event_material_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='QrAttendanceApp.event')),
            ],
        ),
    ]
